### ISSUE TITLE
Three Main Pages

### ISSUE THREAD

**Issue by JefferyMeverden** [schiltz3/The-DMs-Toolkit#26]
**Story**: _As a user, I want to be able to navigate between the three main pages of the website._

**Acceptance Criteria:**

- Create the template shells of the three main pages for each generator.
- Create a homepage for the website that links to the generator pages.
- Create prototype images for the web pages.
- Establish a theme for the website in Bootstrap.

**Comment by johnrtabor** [comment]
This issue was split into multiple separate issues, so it can be closed.
